import { Movie, MovieSource } from '@movie-explorer/types'

export const SEED_MOVIES: Movie[] = [
  {
    id: 'seed-1',
    title: 'The Shawshank Redemption',
    rating: 9.3,
    genres: ['Drama'],
    year: 1994,
    description: 'Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.',
    source: MovieSource.DRIVE,
  },
  {
    id: 'seed-2',
    title: 'The Godfather',
    rating: 9.2,
    genres: ['Crime', 'Drama'],
    year: 1972,
    description: 'The aging patriarch of an organized crime dynasty transfers control to his reluctant son.',
    source: MovieSource.DRIVE,
  },
  {
    id: 'seed-3',
    title: 'The Dark Knight',
    rating: 9.0,
    genres: ['Action', 'Crime', 'Drama'],
    year: 2008,
    description: 'When the menace known as the Joker wreaks havoc on Gotham City, Batman must accept one of the greatest tests of his ability to fight injustice.',
    source: MovieSource.DRIVE,
  },
  {
    id: 'seed-4',
    title: 'Pulp Fiction',
    rating: 8.9,
    genres: ['Crime', 'Drama'],
    year: 1994,
    description: 'The lives of two mob hitmen, a boxer, a gangster and his wife intertwine in four tales of violence and redemption.',
    source: MovieSource.DRIVE,
  },
  {
    id: 'seed-5',
    title: 'Schindler\'s List',
    rating: 9.0,
    genres: ['Biography', 'Drama', 'History'],
    year: 1993,
    description: 'In German-occupied Poland during World War II, industrialist Oskar Schindler gradually becomes concerned for his Jewish workforce after witnessing their persecution by the Nazis.',
    source: MovieSource.DRIVE,
  },
  {
    id: 'seed-6',
    title: 'Inception',
    rating: 8.8,
    genres: ['Action', 'Adventure', 'Sci-Fi'],
    year: 2010,
    description: 'A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.',
    source: MovieSource.DRIVE,
  },
  {
    id: 'seed-7',
    title: 'The Matrix',
    rating: 8.7,
    genres: ['Action', 'Sci-Fi'],
    year: 1999,
    description: 'When a beautiful stranger leads a computer hacker to a forbidding underworld, he discovers the shocking truth — the life he knows is the elaborate deception of an evil cyber-intelligence.',
    source: MovieSource.DRIVE,
  },
  {
    id: 'seed-8',
    title: 'Goodfellas',
    rating: 8.7,
    genres: ['Biography', 'Crime', 'Drama'],
    year: 1990,
    description: 'The story of Henry Hill and his life in the mob, covering his relationship with his wife Karen Hill and his mob partners Jimmy Conway and Tommy DeVito.',
    source: MovieSource.DRIVE,
  },
  {
    id: 'seed-9',
    title: 'Fight Club',
    rating: 8.8,
    genres: ['Drama'],
    year: 1999,
    description: 'An insomniac office worker and a devil-may-care soap maker form an underground fight club that evolves into much more.',
    source: MovieSource.DRIVE,
  },
  {
    id: 'seed-10',
    title: 'Interstellar',
    rating: 8.7,
    genres: ['Adventure', 'Drama', 'Sci-Fi'],
    year: 2014,
    description: 'A team of explorers travel through a wormhole in space in an attempt to ensure humanity\'s survival.',
    source: MovieSource.DRIVE,
  },
  {
    id: 'seed-11',
    title: 'Parasite',
    rating: 8.5,
    genres: ['Comedy', 'Drama', 'Thriller'],
    year: 2019,
    description: 'Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the destitute Kim clan.',
    source: MovieSource.DRIVE,
  },
  {
    id: 'seed-12',
    title: 'Spirited Away',
    rating: 8.6,
    genres: ['Animation', 'Adventure', 'Family'],
    year: 2001,
    description: 'During her family\'s move to the suburbs, a sullen 10-year-old girl wanders into a world ruled by gods, witches, and spirits.',
    source: MovieSource.DRIVE,
  },
]
